
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author rsk
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Crear
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crearExamen = new javax.swing.JButton();
        crearClase = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        crearPregunta = new javax.swing.JButton();
        verClases = new javax.swing.JButton();
        calificaciones = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        crearExamen.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        crearExamen.setText("Crear Nuevo Examen");
        crearExamen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearExamenMouseClicked(evt);
            }
        });
        getContentPane().add(crearExamen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 274, -1));

        crearClase.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        crearClase.setText("Crear Nueva Clase");
        crearClase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearClaseMouseClicked(evt);
            }
        });
        getContentPane().add(crearClase, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 274, -1));

        jButton3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton3.setText("Crear Categoria");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 274, -1));

        crearPregunta.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        crearPregunta.setText("Crear Nueva Pregunta");
        getContentPane().add(crearPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 274, -1));

        verClases.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        verClases.setText("Ver Clases");
        getContentPane().add(verClases, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 274, -1));

        calificaciones.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        calificaciones.setText("Ir a centro de Calificaciones");
        getContentPane().add(calificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 274, -1));

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconfinder-498-student-notes-note-education-4212916_114953.png"))); // NOI18N
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 100, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/textura-fondo-registro-antiguo_24637-351.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearExamenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearExamenMouseClicked
        // TODO add your handling code here:
        CrearExamen creaExam=new CrearExamen();
        creaExam.setVisible(true);
        
    }//GEN-LAST:event_crearExamenMouseClicked

    private void crearClaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearClaseMouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_crearClaseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calificaciones;
    private javax.swing.JButton crearClase;
    private javax.swing.JButton crearExamen;
    private javax.swing.JButton crearPregunta;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton verClases;
    // End of variables declaration//GEN-END:variables
}
